### 1. Criar um array com 10 números inteiros aleatórios entre 1 e 50 e calcular a média e o desvio padrão

In [0]:
import numpy as np

In [0]:
arr1 = np.random.randint(1,51,10) #de 1 a 51 para pegar o 50 (tipo o range)
media1 = np.mean(arr1)
dp1 = np.std(arr1)
print("A média é {} e o desvio padrão é {}".format(media1,dp1))

A média é 26.7 e o desvio padrão é 17.590054007876155


### 2. Criar um array de 10 números aleatórios e calcular a raiz quadrada de todos os valores menores ou iguais a 0,5

In [0]:
arr2 = np.random.rand(10)
arr2

Out[19]: array([0.99462684, 0.31237146, 0.66228619, 0.28503549, 0.16799029,
       0.51039047, 0.60976198, 0.57057085, 0.21617829, 0.31220711])

In [0]:
arr2[arr2 <= 0.5] = np.sqrt(arr2[arr2 <= 0.5])

print(arr2)

[0.99462684 0.55890201 0.66228619 0.53388715 0.40986618 0.51039047
 0.60976198 0.57057085 0.46494977 0.55875496]


### 3. Criar uma matriz 3D de tamanho 3x3x3 com valores aleatórios e exibir o valor máximo de cada linha de cada matriz 2D dentro dessa matriz 3D

In [0]:
matriz3 = np.random.rand(3, 3, 3)
print(matriz3)
max3 = np.amax(matriz3, axis = 1) #trabalhar com amax quando quero obter um max de um 2D de um 3D
print("Valores maximos de cada linha de cada matriz 2D: ", max3)

[[[0.79963352 0.08542403 0.76277095]
  [0.1117511  0.42356401 0.68743121]
  [0.66085258 0.47089001 0.38954436]]

 [[0.46738588 0.93295692 0.5950313 ]
  [0.20149544 0.38970812 0.39236865]
  [0.20767122 0.9239765  0.35782133]]

 [[0.8598905  0.85761284 0.98503919]
  [0.37051719 0.05193294 0.08491308]
  [0.44084957 0.65580453 0.64134218]]]
Valores maximos de cada linha de cada matriz 2D:  [[0.79963352 0.47089001 0.76277095]
 [0.46738588 0.93295692 0.5950313 ]
 [0.8598905  0.85761284 0.98503919]]


### 4. Criar uma matriz de tamanho 5x5 com valores aleatórios e subtrair a média de cada linha dessa matriz

In [0]:
matriz4 = np.random.rand(5, 5)
matriz4

Out[25]: array([[0.80224281, 0.78636374, 0.49742977, 0.54099556, 0.36937404],
       [0.67912489, 0.72040786, 0.09875949, 0.81416696, 0.00903442],
       [0.5142015 , 0.94343311, 0.38023718, 0.28193514, 0.10979432],
       [0.95421224, 0.06285551, 0.08557309, 0.61354145, 0.35323607],
       [0.22111412, 0.37915872, 0.70636375, 0.39174591, 0.01427787]])

In [0]:
media4 = np.mean(matriz4, axis = 1) #axis = 1 é a linha, axis = 0 é coluna
print("A média de cada linha da matriz4 é: ",media4)

matriz_menos_media = matriz4 - media4[:, np.newaxis] #np.newaxis transformando a linha da media em coluna para subtrair da matriz original
print("Matriz menos a média: ", matriz_menos_media)

A média de cada linha da matriz4 é:  [0.59928118 0.46429872 0.44592025 0.41388367 0.34253208]
Matriz menos a média:  [[ 0.20296162  0.18708256 -0.10185142 -0.05828562 -0.22990714]
 [ 0.21482616  0.25610913 -0.36553923  0.34986823 -0.4552643 ]
 [ 0.06828125  0.49751285 -0.06568307 -0.16398511 -0.33612593]
 [ 0.54032857 -0.35102817 -0.32831058  0.19965778 -0.0606476 ]
 [-0.12141795  0.03662664  0.36383168  0.04921383 -0.32825421]]


### 5. Criar uma matriz de tamanho 4x4 com valores aleatórios e calcular a média e o desvio padrão das diagonais da matriz

In [0]:
matriz5 = np.random.rand(4, 4)
matriz5

Out[32]: array([[0.98433281, 0.02421157, 0.38529854, 0.00449432],
       [0.26142767, 0.26342634, 0.8981061 , 0.21368996],
       [0.9679471 , 0.62890484, 0.27889101, 0.25007669],
       [0.74671751, 0.31157927, 0.50346409, 0.99747305]])

In [0]:
diag_principal = np.diag(matriz5)
diag_secund = np.diag(np.fliplr(matriz5)) #função dentro da função
 
media_diagonais = np.mean([diag_principal, diag_secund])
dp_diagonais = np.std([diag_principal,diag_secund])


print("A média das diagonais é:", media_diagonais)
print("O desvio padrão das diagonais é: ", dp_diagonais)

A média das diagonais é: 0.600293247560532
O desvio padrão das diagonais é:  0.3514157868584697
